### ISSUE TITLE
Some questions related to package installation 

### ISSUE THREAD

**Issue by HelloWorldLTY** [shbrief/GenomicSuperSignaturePaper#1]
Hi, I find that using the codes given in the readme file, the installation process of GSSP will fail.
![image](https://user-images.githubusercontent.com/43333475/177362616-1dad08da-1b5c-47a3-9415-8dec82d87b14.png)
The error looks like this. Could you please help me resolve it? Thanks a lot!

**Comment by shbrief** [comment]
Sorry, it was a wrong function -  should use `devtools::install_github("shbrief/GenomicSuperSignaturePaper)`.
I corrected it in the latest commit: 64478d4ed42c0e318fedece8e1aaf3feeaf3c130.
Thanks for finding it out.

**Comment by HelloWorldLTY** [comment]
Thanks a lot!

**Comment by HelloWorldLTY** [comment]
In addition, I also find that this package does not include the gene sets of C2. We can download that gmt file via this link:
http://www.gsea-msigdb.org/gsea/downloads.jsp#msigdb

**Comment by shbrief** [comment]
@HelloWorldLTY 
This package is not for the RAVmodel building, so there is no need to include C2 gene sets. Also, R packages should only contain minimal datasets for the purpose of providing examples. C2 gene sets, for example, can be easily loaded using `EnrichmentBrowser` package. 
(e.g. `EnrichmentBrowser::getGenesets(org = "hsa", db = "msigdb", cat = "C2", gene.id.type = "SYMBOL")`)
